### ISSUE TITLE
Update to browserify 5

### ISSUE THREAD

**Issue by mikehedman** [HenrikJoreteg/moonboots#39]
I was just starting up a new Ampersand project, and on first run (npm i && npm start)got this error:
Error: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor.
    at Browserify.bundle (/Users/mike/dev/node/datatables/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/index.js:564:15)
    at async.series.mdeps.resolve (/Users/mike/dev/node/datatables/node_modules/moonboots-express/node_modules/moonboots/index.js:351:20)
    at /Users/mike/dev/node/datatables/node_modules/async/lib/async.js:610:21
    at /Users/mike/dev/node/datatables/node_modules/async/lib/async.js:249:17
    at iterate (/Users/mike/dev/node/datatables/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/Users/mike/dev/node/datatables/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/Users/mike/dev/node/datatables/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/Users/mike/dev/node/datatables/node_modules/async/lib/async.js:231:23)
    at Object.async.series (/Users/mike/dev/node/datatables/node_modules/async/lib/async.js:608:19)
    at Moonboots.browserify (/Users/mike/dev/node/datatables/node_modules/moonboots-express/node_modules/moonboots/index.js:348:11)

I wish I could give you more info... I have stopped and restarted the node app and now the error message is no longer displayed.  I've tried a number of things, but could not reproduce it.  There is some internet chatter about a Browserify API change in their version 5.

**Comment by lukekarrys** [comment]
Closed by #62
