### ISSUE TITLE
Error - too many open files

### ISSUE THREAD

**Issue by getdave** [HenrikJoreteg/moonboots#68]
Running a standard AmpJS app using the CLI. 

`node server` reports app being served at localhost.

Navigate to localhost in Chrome.

Server falls over with Moonboots related error.

```js
Diabetix is running at: http://localhost:3000 Yep. That's pretty awesome.

/Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/index.js:546
                : opts.basedir || process.cwd()
                                          ^
Error: EMFILE, too many open files
    at globalTr (/Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/index.js:546:43)
    at makeTransform (/Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/module-deps/index.js:250:21)
    at /Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/module-deps/index.js:225:9
    at Deps.getTransforms (/Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/module-deps/index.js:230:7)
    at /Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/module-deps/index.js:365:24
    at onresolve (/Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/module-deps/index.js:177:14)
    at /Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/index.js:475:13
    at /Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/browser-resolve/index.js:254:13
    at /Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/resolve/lib/async.js:44:21
    at ondir (/Users/davidsmith1/Sites/ampersand-app/node_modules/moonboots-express/node_modules/moonboots/node_modules/browserify/node_modules/resolve/lib/async.js:187:31)
```

Any help much appreciated.

**Comment by lukekarrys** [comment]
@getdave Do any of the suggestions in this issue work for you? https://github.com/AmpersandJS/ampersand/issues/117
